name: Test Docker Hub Setup

on:
  workflow_dispatch: # Manual trigger only

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test-docker-hub:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Test Docker Hub login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Test Docker build (no push)
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:test
        platforms: linux/amd64

    - name: Test success
      run: |
        echo "✅ Docker Hub setup test completed successfully!"
        echo "Username: ${{ secrets.DOCKERHUB_USERNAME }}"
        echo "Repository: ${{ env.IMAGE_NAME }}"
        echo "Image would be: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:test" 